use super::SpecMeta;

/// Render the provenance header comment stamped atop generated files: the spargen version and the
/// source spec identity, for traceability and to make regeneration auditable.
pub fn provenance_header(spec: &SpecMeta) -> String {
    format!(
        "// @generated by spargen {}\n// source: {}\n// deterministic: same spargen version + spec + config => same bytes\n\n",
        spec.spargen_version, spec.source
    )
}
