//! # Subsystem: emit
//! layer-deps: codegen, diag
//!
//! Module assembly and provenance stamping. Emit turns
//! [`GeneratedCode`](crate::codegen::GeneratedCode) into one deterministic module plan.

mod header;

use crate::codegen::{GeneratedCode, GeneratedFile};

pub use header::provenance_header;

/// Identity of the source spec, stamped into the provenance header.
#[derive(Debug, Clone)]
pub(crate) struct SpecMeta {
    /// A description of the source spec (path or URL as vendored).
    pub source: String,
    /// The spargen version that produced the output.
    pub spargen_version: String,
}

/// Options for one emission.
#[derive(Debug, Clone)]
pub(crate) struct EmitOptions {
    /// Spec provenance to stamp.
    pub spec: SpecMeta,
}

/// A fully-rendered emission plan with its final on-disk contents and provenance header.
#[derive(Debug, Clone, Default)]
pub(crate) struct EmitPlan {
    /// The files to write, in deterministic order.
    pub files: Vec<GeneratedFile>,
}

/// An emission failure.
#[derive(Debug)]
pub(crate) enum EmitError {
    /// A filesystem error.
    Io(std::io::Error),
    /// The requested layout is inconsistent with the generated code.
    Layout(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Io(e) => write!(f, "emit I/O error: {e}"),
            EmitError::Layout(msg) => write!(f, "emit layout error: {msg}"),
        }
    }
}

impl std::error::Error for EmitError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            EmitError::Io(e) => Some(e),
            EmitError::Layout(_) => None,
        }
    }
}

impl From<std::io::Error> for EmitError {
    fn from(e: std::io::Error) -> Self {
        EmitError::Io(e)
    }
}

/// Build the on-disk emission plan from generated code and options: stamp the provenance header
/// onto the single generated module. Spargen writes one `include!`-safe file and nothing else —
/// the consuming package owns its own `Cargo.toml`.
pub(crate) fn plan(code: &GeneratedCode, options: &EmitOptions) -> Result<EmitPlan, EmitError> {
    let header = provenance_header(&options.spec);
    let mut files = Vec::new();
    let Some(file) = code.files.first() else {
        return Err(EmitError::Layout("codegen produced no files".to_owned()));
    };
    files.push(GeneratedFile {
        contents: format!("{header}{}", file.contents),
    });
    Ok(EmitPlan { files })
}

#[cfg(test)]
mod tests {
    use super::{plan, EmitError, EmitOptions, SpecMeta};
    use crate::codegen::{GeneratedCode, GeneratedFile};

    fn options() -> EmitOptions {
        EmitOptions {
            spec: SpecMeta {
                source: "openapi.yaml omit=0123456789abcdef".to_owned(),
                spargen_version: "9.9.9".to_owned(),
            },
        }
    }

    fn code(contents: &str) -> GeneratedCode {
        GeneratedCode {
            files: vec![GeneratedFile {
                contents: contents.to_owned(),
            }],
        }
    }

    /// The header is this subsystem's entire output, and it is what makes a regeneration
    /// auditable: which spargen produced the file, from which spec, under which omit profile.
    #[test]
    fn the_plan_stamps_provenance_ahead_of_the_generated_module() {
        let plan = plan(&code("pub struct Api;\n"), &options()).unwrap();
        let contents = &plan.files[0].contents;

        assert!(
            contents.starts_with("// @generated by spargen 9.9.9\n"),
            "{contents}"
        );
        assert!(
            contents.contains("// source: openapi.yaml omit=0123456789abcdef\n"),
            "{contents}"
        );
        assert!(
            contents
                .contains("// deterministic: same spargen version + spec + config => same bytes"),
            "{contents}"
        );
        assert!(
            contents.ends_with("pub struct Api;\n"),
            "the generated module must follow the header verbatim: {contents}"
        );
    }

    /// Generated output is consumed via `include!`, so the header must be comments only — a
    /// crate-level inner attribute here would break every consumer.
    #[test]
    fn the_header_is_comments_only_and_include_safe() {
        let plan = plan(&code("pub struct Api;\n"), &options()).unwrap();
        let header: Vec<&str> = plan.files[0]
            .contents
            .lines()
            .take_while(|line| !line.starts_with("pub "))
            .filter(|line| !line.trim().is_empty())
            .collect();

        assert!(!header.is_empty());
        for line in header {
            assert!(
                line.starts_with("//"),
                "header line is not a comment: {line}"
            );
            assert!(!line.starts_with("#!"), "inner attribute in header: {line}");
        }
    }

    #[test]
    fn the_plan_is_deterministic_for_the_same_inputs() {
        let first = plan(&code("pub struct Api;\n"), &options()).unwrap();
        let second = plan(&code("pub struct Api;\n"), &options()).unwrap();
        assert_eq!(first.files[0].contents, second.files[0].contents);
    }

    /// Spargen writes exactly one `include!`-safe file; the consuming package owns everything
    /// else. Emitting a second would silently create a file no consumer includes.
    #[test]
    fn the_plan_emits_exactly_one_file() {
        let mut multiple = code("pub struct Api;\n");
        multiple.files.push(GeneratedFile {
            contents: "pub struct Extra;\n".to_owned(),
        });
        let plan = plan(&multiple, &options()).unwrap();
        assert_eq!(plan.files.len(), 1);
        assert!(plan.files[0].contents.contains("pub struct Api;"));
    }

    #[test]
    fn an_empty_codegen_result_is_a_layout_error_not_an_empty_file() {
        let error = plan(&GeneratedCode { files: Vec::new() }, &options()).unwrap_err();
        assert!(matches!(error, EmitError::Layout(_)), "{error}");
        assert_eq!(
            error.to_string(),
            "emit layout error: codegen produced no files"
        );
        assert!(std::error::Error::source(&error).is_none());
    }

    #[test]
    fn an_io_error_keeps_its_cause_in_the_chain() {
        let error = EmitError::from(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            "denied",
        ));
        assert!(matches!(error, EmitError::Io(_)));
        assert!(error.to_string().starts_with("emit I/O error: "));
        assert!(
            std::error::Error::source(&error).is_some(),
            "an I/O failure must keep the underlying error reachable"
        );
    }
}
