//! The `spargen.lock` pin file and its vendor-directory layout.
//!
//! Remote (`http`/`https`) `$ref` resolution is hermetic: `generate`/`check` never touch the
//! network. Instead a remote document is resolved only from a locally vendored copy whose bytes are
//! hash-pinned in a lock file that sits next to the spec. The lock is the source of truth — vendored
//! content that does not match its `sha256` is refused rather than silently used.
//!
//! The lock is a small, deterministic TOML file (sorted by URL, no timestamps) so the same
//! spec + lock always produce byte-identical output and the lock diffs cleanly in review:
//!
//! ```toml
//! version = 1
//!
//! [[remote]]
//! url = "https://example.com/schemas/pet.yaml"
//! sha256 = "…64 hex chars…"
//! path = "example.com/schemas/pet.yaml"
//! ```
//!
//! `path` is relative to the vendor directory ([`VENDOR_DIR`], `.spargen/vendor/` beside the spec),
//! so the lock carries no machine-specific absolute paths.

#[cfg(feature = "remote-fetch")]
use std::fmt::Write as _;

/// The lock file name, looked up next to the root spec.
pub(crate) const LOCK_FILE_NAME: &str = "spargen.lock";

/// The vendor directory (relative to the spec's directory) holding pinned remote documents.
pub(crate) const VENDOR_DIR: &str = ".spargen/vendor";

/// The only lock schema version understood by this build.
const LOCK_VERSION: u32 = 1;

/// One pinned remote document.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RemoteEntry {
    /// The absolute `http`/`https` URL the document was fetched from (fragment stripped).
    pub url: String,
    /// Lowercase hex SHA-256 of the fetched bytes.
    pub sha256: String,
    /// Path of the vendored copy, relative to [`VENDOR_DIR`].
    pub path: String,
}

/// The parsed `spargen.lock`: a set of pinned remote documents, kept sorted by URL.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct Lock {
    entries: Vec<RemoteEntry>,
}

/// A lock-file parse failure (malformed TOML or an unknown schema version).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LockError(pub String);

impl std::fmt::Display for LockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl Lock {
    /// Look up the pin for an absolute base URL (fragment already stripped).
    pub(crate) fn get(&self, url: &str) -> Option<&RemoteEntry> {
        self.entries.iter().find(|entry| entry.url == url)
    }

    /// Insert or replace the pin for `entry.url`, keeping entries sorted by URL.
    #[cfg(feature = "remote-fetch")]
    pub(crate) fn upsert(&mut self, entry: RemoteEntry) {
        if let Some(existing) = self.entries.iter_mut().find(|e| e.url == entry.url) {
            *existing = entry;
        } else {
            self.entries.push(entry);
        }
        self.entries.sort_by(|a, b| a.url.cmp(&b.url));
    }

    /// Render the lock to deterministic TOML: `version` first, then each `[[remote]]` table in
    /// URL order. No timestamps, so the output is a pure function of the pins.
    #[cfg(feature = "remote-fetch")]
    pub(crate) fn to_toml(&self) -> String {
        let mut sorted = self.entries.clone();
        sorted.sort_by(|a, b| a.url.cmp(&b.url));
        let mut out = String::new();
        let _ = writeln!(out, "# Generated by `spargen lock`. Do not edit by hand.");
        let _ = writeln!(out, "version = {LOCK_VERSION}");
        for entry in &sorted {
            out.push('\n');
            let _ = writeln!(out, "[[remote]]");
            let _ = writeln!(out, "url = {}", toml_string(&entry.url));
            let _ = writeln!(out, "sha256 = {}", toml_string(&entry.sha256));
            let _ = writeln!(out, "path = {}", toml_string(&entry.path));
        }
        out
    }

    /// Parse a `spargen.lock`. The format is the fixed, machine-written schema above; this reader is
    /// deliberately small and rejects anything it does not understand rather than guessing.
    pub(crate) fn parse(text: &str) -> Result<Lock, LockError> {
        let mut lock = Lock::default();
        let mut version_seen = false;
        let mut current: Option<PartialEntry> = None;

        for (lineno, raw) in text.lines().enumerate() {
            let line = strip_comment(raw).trim();
            if line.is_empty() {
                continue;
            }
            if line == "[[remote]]" {
                if let Some(entry) = current.take() {
                    lock.push_partial(entry, lineno)?;
                }
                current = Some(PartialEntry::default());
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                return Err(LockError(format!(
                    "spargen.lock line {}: expected `key = value`",
                    lineno + 1
                )));
            };
            let key = key.trim();
            let value = value.trim();
            if let Some(entry) = current.as_mut() {
                let text = parse_toml_string(value).ok_or_else(|| {
                    LockError(format!(
                        "spargen.lock line {}: `{key}` must be a quoted string",
                        lineno + 1
                    ))
                })?;
                match key {
                    "url" => entry.url = Some(text),
                    "sha256" => entry.sha256 = Some(text),
                    "path" => entry.path = Some(text),
                    other => {
                        return Err(LockError(format!(
                            "spargen.lock line {}: unknown key `{other}` in [[remote]]",
                            lineno + 1
                        )))
                    }
                }
            } else if key == "version" {
                let version: u32 = value.parse().map_err(|_| {
                    LockError(format!("spargen.lock line {}: invalid version", lineno + 1))
                })?;
                if version != LOCK_VERSION {
                    return Err(LockError(format!(
                        "spargen.lock declares unsupported version {version} (expected {LOCK_VERSION})"
                    )));
                }
                version_seen = true;
            } else {
                return Err(LockError(format!(
                    "spargen.lock line {}: unexpected key `{key}` before any [[remote]] table",
                    lineno + 1
                )));
            }
        }
        if let Some(entry) = current.take() {
            lock.push_partial(entry, text.lines().count())?;
        }
        if !version_seen {
            return Err(LockError("spargen.lock is missing `version`".to_owned()));
        }
        lock.entries.sort_by(|a, b| a.url.cmp(&b.url));
        Ok(lock)
    }

    fn push_partial(&mut self, partial: PartialEntry, lineno: usize) -> Result<(), LockError> {
        let entry = partial.finish().ok_or_else(|| {
            LockError(format!(
                "spargen.lock: [[remote]] before line {} is missing url/sha256/path",
                lineno + 1
            ))
        })?;
        // Security: `path` is later joined onto the vendor dir and read from disk. A hand-edited or
        // committed lock must never be able to point that read outside the vendor directory, so an
        // absolute path, a drive/root prefix, or any `..` component is rejected here — before any
        // file is opened — rather than trusting the on-disk lock.
        validate_vendor_path(&entry.path)?;
        self.entries.push(entry);
        Ok(())
    }
}

/// Reject a vendor `path` that could escape the vendor directory when joined and read. Rejected:
/// an empty path, an absolute path or one with a root/drive prefix, and any `..` (parent) component.
fn validate_vendor_path(path: &str) -> Result<(), LockError> {
    use camino::{Utf8Component, Utf8Path};

    if path.is_empty() {
        return Err(LockError(
            "spargen.lock: a [[remote]] path is empty".to_owned(),
        ));
    }
    for component in Utf8Path::new(path).components() {
        match component {
            Utf8Component::Normal(_) | Utf8Component::CurDir => {}
            Utf8Component::ParentDir => {
                return Err(LockError(format!(
                    "spargen.lock: vendor path `{path}` must not contain `..` (would escape the vendor directory)"
                )));
            }
            Utf8Component::RootDir | Utf8Component::Prefix(_) => {
                return Err(LockError(format!(
                    "spargen.lock: vendor path `{path}` must be relative to the vendor directory"
                )));
            }
        }
    }
    Ok(())
}

#[derive(Debug, Default)]
struct PartialEntry {
    url: Option<String>,
    sha256: Option<String>,
    path: Option<String>,
}

impl PartialEntry {
    fn finish(self) -> Option<RemoteEntry> {
        Some(RemoteEntry {
            url: self.url?,
            sha256: self.sha256?,
            path: self.path?,
        })
    }
}

/// Derive a deterministic, filesystem-safe vendor path for an absolute URL. `https://host/a/b.yaml`
/// maps to `host/a/b.yaml`; every path segment is sanitized so the result never escapes the vendor
/// directory (`..` and separators are neutralized).
#[cfg(feature = "remote-fetch")]
pub(crate) fn vendor_path_for_url(url: &str) -> String {
    let without_scheme = url.split_once("://").map(|(_, rest)| rest).unwrap_or(url);
    let without_query = without_scheme
        .split(['?', '#'])
        .next()
        .unwrap_or(without_scheme);
    let mut segments: Vec<String> = Vec::new();
    for segment in without_query.split('/') {
        let sanitized = sanitize_segment(segment);
        if sanitized.is_empty() || sanitized == "." {
            continue;
        }
        if sanitized == ".." {
            // Never allow traversal above the vendor root.
            segments.push("__".to_owned());
            continue;
        }
        segments.push(sanitized);
    }
    if segments.is_empty() {
        segments.push("index".to_owned());
    }
    segments.join("/")
}

#[cfg(feature = "remote-fetch")]
fn sanitize_segment(segment: &str) -> String {
    segment
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '.' | '-' | '_') {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn strip_comment(line: &str) -> &str {
    // Comments only start a line or follow whitespace; `#` inside a quoted value is preserved
    // because values here are URLs/hashes/paths that never contain `#` after fragment stripping.
    match line.find('#') {
        Some(idx) => &line[..idx],
        None => line,
    }
}

#[cfg(feature = "remote-fetch")]
fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn parse_toml_string(value: &str) -> Option<String> {
    let inner = value.strip_prefix('"')?.strip_suffix('"')?;
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(ch) = chars.next() {
        if ch == '\\' {
            match chars.next()? {
                '"' => out.push('"'),
                '\\' => out.push('\\'),
                _ => return None,
            }
        } else {
            out.push(ch);
        }
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "remote-fetch")]
    #[test]
    fn round_trips_deterministically() {
        let mut lock = Lock::default();
        lock.upsert(RemoteEntry {
            url: "https://b.example/z.yaml".to_owned(),
            sha256: "beef".to_owned(),
            path: "b.example/z.yaml".to_owned(),
        });
        lock.upsert(RemoteEntry {
            url: "https://a.example/y.yaml".to_owned(),
            sha256: "cafe".to_owned(),
            path: "a.example/y.yaml".to_owned(),
        });
        let toml = lock.to_toml();
        // Sorted by URL regardless of insertion order.
        let a = toml.find("a.example/y.yaml").unwrap();
        let b = toml.find("b.example/z.yaml").unwrap();
        assert!(a < b, "entries must be URL-sorted:\n{toml}");
        let reparsed = Lock::parse(&toml).unwrap();
        assert_eq!(reparsed, lock);
        assert_eq!(reparsed.to_toml(), toml, "serialization is a fixed point");
    }

    #[test]
    fn rejects_unknown_version() {
        let err = Lock::parse("version = 2\n").unwrap_err();
        assert!(err.0.contains("unsupported version"), "{err}");
    }

    #[test]
    fn rejects_traversal_and_absolute_vendor_paths() {
        // Security: a lock that would escape the vendor directory must fail at parse, before any
        // file read.
        let traversal =
            "version = 1\n[[remote]]\nurl = \"https://h/x\"\nsha256 = \"a\"\npath = \"../../etc/passwd\"\n";
        let err = Lock::parse(traversal).unwrap_err();
        assert!(err.0.contains(".."), "{err}");

        let absolute =
            "version = 1\n[[remote]]\nurl = \"https://h/x\"\nsha256 = \"a\"\npath = \"/etc/passwd\"\n";
        let err = Lock::parse(absolute).unwrap_err();
        assert!(err.0.contains("relative"), "{err}");
    }

    #[test]
    fn rejects_missing_version() {
        let err =
            Lock::parse("[[remote]]\nurl = \"x\"\nsha256 = \"y\"\npath = \"z\"\n").unwrap_err();
        assert!(err.0.contains("missing `version`"), "{err}");
    }

    #[cfg(feature = "remote-fetch")]
    #[test]
    fn vendor_path_is_sanitized() {
        assert_eq!(
            vendor_path_for_url("https://example.com/a/b.yaml"),
            "example.com/a/b.yaml"
        );
        // Traversal and odd characters can never escape the vendor root.
        let path = vendor_path_for_url("https://evil.test/../../etc/passwd");
        assert!(!path.contains(".."), "{path}");
        assert!(!path.starts_with('/'), "{path}");
    }
}
