//! CLI-surface tests that drive the real `spargen` binary (via `CARGO_BIN_EXE_spargen`) — the only
//! way to assert on process stdout/stderr and exit codes as a user sees them. Kept minimal: the
//! generation pipeline itself is covered by `e2e.rs`; here we pin the CLI's own contracts.

use std::process::Command;

/// A minimal but complete 3.1 spec: one operation, one model. Enough to render a module.
const TINY_SPEC: &str = r##"
openapi: 3.1.0
info: { title: Tiny, version: 1.0.0 }
paths:
  /widgets/{id}:
    get:
      operationId: getWidget
      parameters:
        - { name: id, in: path, required: true, schema: { type: string } }
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Widget" }
components:
  schemas:
    Widget:
      type: object
      required: [id]
      properties:
        id: { type: string }
"##;

/// `spargen` binary path, provided to integration tests by cargo.
fn spargen_bin() -> &'static str {
    env!("CARGO_BIN_EXE_spargen")
}

/// `generate <spec> --out -` prints the rendered module to stdout (nothing to disk), so it can be
/// piped to `rustfmt` / a pager. Diagnostics, if any, go to stderr — stdout stays pure code.
#[test]
fn generate_out_dash_prints_module_to_stdout() {
    let temp = tempfile::tempdir().unwrap();
    let spec = temp.path().join("openapi.yaml");
    std::fs::write(&spec, TINY_SPEC).unwrap();

    let output = Command::new(spargen_bin())
        .args(["generate", spec.to_str().unwrap(), "--out", "-"])
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "expected success, got {:?}; stderr: {}",
        output.status,
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(
        stdout.starts_with("// @generated by spargen"),
        "stdout must be the rendered module (provenance header first): {stdout}"
    );
    assert!(
        stdout.contains("pub struct Widget"),
        "stdout must contain the generated model: {stdout}"
    );
    // The dash is a stream target, not a filename: no file literally named "-" is created.
    assert!(
        !std::path::Path::new("-").exists(),
        "a file named '-' must not be written to the working directory"
    );
}

/// `--out -` is a single-module preview, so combining it with `--as-crate` (multiple files) is a
/// usage error: non-zero exit, message on stderr, and no code leaked to stdout.
#[test]
fn generate_out_dash_with_as_crate_is_a_usage_error() {
    let temp = tempfile::tempdir().unwrap();
    let spec = temp.path().join("openapi.yaml");
    std::fs::write(&spec, TINY_SPEC).unwrap();

    let output = Command::new(spargen_bin())
        .args([
            "generate",
            spec.to_str().unwrap(),
            "--out",
            "-",
            "--as-crate",
        ])
        .output()
        .unwrap();

    assert!(
        !output.status.success(),
        "must fail for --out - with --as-crate"
    );
    assert!(
        output.stdout.is_empty(),
        "no code must be printed to stdout on a usage error"
    );
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.contains("--as-crate"),
        "stderr must explain the incompatible flags: {stderr}"
    );
}
