//! Drives the generated petstore client end to end against a local mock server: typed models,
//! query/header/path parameters, JSON bodies, bearer auth (a static token and an async token
//! provider, succeeding and failing), typed API errors, RFC 9457 problems read generically (one
//! with a problem type the description does not list), undocumented-status
//! handling, a refused connection, the transient-failure classifier, and the bring-your-own-policy retry adapter.
//! Everything runs on 127.0.0.1 — no external API, no real credentials.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::Arc;
use std::time::Duration;

use secrecy::SecretString;

// The client generated by build.rs. Its file carries no inner attributes, so it can be included
// straight from OUT_DIR. A build.rs may instead target `src/petstore.rs` for committed output.
mod petstore {
    include!(concat!(env!("OUT_DIR"), "/petstore.rs"));
}

use petstore::{
    exponential_backoff, types, ApiErrorProblem, AuthError, Client, CreatePetError, Credential,
    Error, HttpBackend, RequestError, ReqwestBackend, RetryBackend, RetryOutcome, RetryPolicy,
    RetryWait, TokenFuture,
};

const TOKEN: &str = "let-me-in";

/// How many times the flaky route has been hit; it fails transiently (503) on the first attempt,
/// then serves 200 — so a retrying client succeeds where a plain one would surface the 503.
static FLAKY_HITS: AtomicU32 = AtomicU32::new(0);

/// How many requests the mock has read a request line for, so a scenario can assert that a
/// pre-send failure put nothing on the wire.
static MOCK_REQUESTS: AtomicU32 = AtomicU32::new(0);

/// How many times the token provider has been asked for a token.
static PROVIDER_CALLS: AtomicU32 = AtomicU32::new(0);

/// A bring-your-own retry policy: retry transient outcomes with exponential backoff, up to a cap.
/// The wait is built from the caller's own async timer (`tokio::time::sleep`) — the spargen runtime
/// ships no timer and never depends on tokio; timing is supplied here.
///
/// `RetryWait` is re-exported by the generated client, so the policy names the runtime's own alias
/// rather than spelling out `Pin<Box<dyn Future<Output = ()> + Send + 'a>>` by hand.
struct ExponentialBackoff {
    max_retries: u32,
}

impl RetryPolicy for ExponentialBackoff {
    fn retry<'a>(&'a self, attempt: u32, outcome: &RetryOutcome<'_>) -> Option<RetryWait<'a>> {
        if attempt < self.max_retries && outcome.is_transient() {
            let wait = exponential_backoff(
                attempt,
                Duration::from_millis(10),
                Duration::from_millis(200),
            );
            Some(Box::pin(tokio::time::sleep(wait)))
        } else {
            None
        }
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let addr = spawn_mock_server();
    let base_url = format!("http://{addr}");
    println!("mock petstore listening on {base_url}");

    let client = Client::new(&base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));

    // The spec's server is templated (`http://{host}:{port}`), so spargen generates a typed builder
    // whose variables default to a resolvable URL. The example dials the mock's ephemeral port
    // instead, but the typed surface is real and is exercised here.
    assert_eq!(petstore::servers::default_url(), "http://127.0.0.1:0");
    assert_eq!(
        petstore::servers::Server0::new()
            .host("example.test")
            .port("8443")
            .url(),
        "http://example.test:8443"
    );

    // List with query + header parameters, built via the fluent optional-param setters. `filter` is
    // a `deepObject`, so each member travels as its own `filter[member]=value` pair.
    let pets = client
        .list_pets(
            petstore::ListPetsParams::default()
                .limit(10)
                .status(types::Status::Available)
                .x_request_id("example-1".to_owned())
                .filter(types::PetFilter {
                    name: Some("Rex".to_owned()),
                    tag: None,
                }),
        )
        .await
        .expect("list_pets");
    assert_eq!(pets.status(), 200);
    // A documented response header is read through a typed accessor — an explicit second step, so a
    // malformed header can never turn a successful call into a failure.
    let totals = petstore::ListPetsStatus200Headers::from_response(&pets).expect("typed headers");
    assert_eq!(totals.x_total_count, 1);
    let pets = pets.into_inner();
    assert_eq!(pets.len(), 1);
    println!(
        "listed {} of {} available pet(s): {}",
        pets.len(),
        totals.x_total_count,
        pets[0].name
    );

    // Create with a typed JSON body.
    let created = client
        .create_pet(&types::NewPet {
            name: "Bella".to_owned(),
            tag: Some("dog".to_owned()),
        })
        .await
        .expect("create_pet");
    assert_eq!(created.status(), 201);
    let created = created.into_inner();
    println!("created pet #{} ({})", created.id, created.name);

    // Fetch by path parameter.
    let pet = client.get_pet("1").await.expect("get_pet");
    assert_eq!(pet.into_inner().status, types::Status::Available);
    println!("fetched pet #1");

    // A documented 404 arrives as the operation's typed error body.
    match client.get_pet("999").await {
        Err(Error::Api(response)) => {
            assert_eq!(response.status(), 404);
            println!("typed 404: {}", response.into_inner().message);
        }
        other => panic!("expected a typed 404, got {other:?}"),
    }

    // RFC 9457 problems. The description narrows `createPet`'s `409` problem `type` to
    // `…/name-taken`, and the server answers with `…/name-reserved`, a type it added after the
    // description was written. `build.rs` turns on `open_narrowing`, so the response is still the
    // typed `409` body rather than a decode failure, and the unlisted type is kept.
    let reserved = client
        .create_pet(&types::NewPet {
            name: "Taken".to_owned(),
            tag: None,
        })
        .await;
    match &reserved {
        Err(Error::Api(response)) => {
            assert_eq!(response.status(), 409);
            let CreatePetError::Status409(problem) = response.inner() else {
                panic!("expected the typed 409 problem, got {response:?}");
            };
            assert_eq!(
                problem.r#type.to_string(),
                "https://petstore.example/problems/name-reserved"
            );
            println!("typed 409 with an unlisted problem type: {}", problem.r#type);
        }
        other => panic!("expected a typed 409, got {other:?}"),
    }
    // One reader, generic over every operation: `createPet` and `deletePet` document different
    // problem bodies, and `Error::problem` reads `type` and `detail` from either.
    fn describe<E: ApiErrorProblem>(error: &Error<E>) -> String {
        let problem = error.problem().expect("a problem body");
        format!(
            "{}: {}",
            problem.problem_type_or_blank(),
            problem.detail.as_deref().unwrap_or_default()
        )
    }
    let Err(reserved) = reserved else {
        unreachable!("matched as an error above");
    };
    assert_eq!(
        describe(&reserved),
        "https://petstore.example/problems/name-reserved: `Taken` is held for a sold pet."
    );
    let Err(has_orders) = client.delete_pet("3").await else {
        panic!("deleting pet 3 must fail with its documented 409");
    };
    assert_eq!(
        describe(&has_orders),
        "https://petstore.example/problems/pet-has-orders: pet 3 has an open order."
    );
    println!("read two operations' problems with one generic reader");

    // A multipart body with an Encoding Object: each part is sent with the Content-Type the spec
    // declares for it — `image/png` for the binary photo, `application/json` for the metadata
    // object — rather than one blanket type for the whole form.
    let stored = client
        .upload_photo(
            "1",
            &types::RequestBody {
                photo: bytes::Bytes::from_static(b"\x89PNG\r\n\x1a\n"),
                meta: types::PhotoMeta {
                    caption: "Rex at the park".to_owned(),
                    width: Some(1024),
                },
            },
        )
        .await
        .expect("upload_photo");
    assert_eq!(stored.status(), 204);
    println!("uploaded a photo with typed multipart part Content-Types");

    // A bodied 200 beside a documented bodyless 204: each status is its own variant, so the empty
    // 204 is a success the caller matches on rather than a failed decode of an empty `Pet`.
    let rename = types::NewPet {
        name: "Rexy".to_owned(),
        tag: None,
    };
    for (pet_id, expected) in [("1", 200), ("2", 204)] {
        let updated = client
            .update_pet(pet_id, &rename)
            .await
            .expect("update_pet");
        assert_eq!(updated.status(), expected);
        match updated.into_inner() {
            petstore::UpdatePetResponse::Status200(pet) => {
                assert_eq!(pet.name, "Rexy");
                println!("updated pet #{pet_id}, server returned it");
            }
            petstore::UpdatePetResponse::Status204 => {
                println!("updated pet #{pet_id}, server returned nothing (204)");
            }
        }
    }

    // 204 maps to a unit body.
    let deleted = client.delete_pet("1").await.expect("delete_pet");
    assert_eq!(deleted.status(), 204);
    println!("deleted pet #1");

    // A missing credential fails before anything is sent — never a silent 401 — and it is typed, so
    // an application can route it to "unauthenticated" rather than to "malformed request".
    let unauthenticated = Client::new(&base_url).unwrap();
    match unauthenticated.get_pet("1").await {
        Err(Error::RequestConstruction(RequestError::MissingCredential { alternatives })) => {
            assert_eq!(alternatives, [vec!["bearerAuth"]]);
            println!("missing credential rejected up front, naming {alternatives:?}");
        }
        other => panic!("expected a missing-credential error, got {other:?}"),
    }

    // A rotating token from an async provider. The closure is awaited on tokio's real executor, and
    // it genuinely suspends (a timer, standing in for a round trip to an identity provider) before
    // yielding, so the request build is held across a pending poll rather than a ready one. The
    // mock accepts only `Bearer let-me-in`, so a 200 proves the provider's token is what travelled.
    // It is asked once per request, not once per client: two calls, two refreshes.
    let rotating = Client::new(&base_url).unwrap().with_credential(
        "bearerAuth",
        Credential::Provider(Arc::new(|| -> TokenFuture {
            Box::pin(async {
                tokio::time::sleep(Duration::from_millis(5)).await;
                PROVIDER_CALLS.fetch_add(1, Ordering::SeqCst);
                Ok(SecretString::from(TOKEN))
            })
        })),
    );
    for _ in 0..2 {
        let pet = rotating
            .get_pet("1")
            .await
            .expect("a provider-supplied token authenticates");
        assert_eq!(pet.status(), 200);
    }
    assert_eq!(PROVIDER_CALLS.load(Ordering::SeqCst), 2);
    println!("token provider awaited on a real executor, once per request");

    // A provider that fails is the client's "unauthenticated" state: typed, naming the scheme, with
    // the provider's own `AuthError` as the cause — and raised before anything is sent, so the mock
    // sees no request for it.
    let failing = Client::new(&base_url).unwrap().with_credential(
        "bearerAuth",
        Credential::Provider(Arc::new(|| -> TokenFuture {
            Box::pin(async {
                tokio::time::sleep(Duration::from_millis(5)).await;
                Err(AuthError::new("identity provider unavailable"))
            })
        })),
    );
    let requests_before = MOCK_REQUESTS.load(Ordering::SeqCst);
    let error = failing
        .get_pet("1")
        .await
        .expect_err("a failing provider must fail the call");
    let Error::RequestConstruction(RequestError::CredentialProvider { scheme, source }) = &error
    else {
        panic!("expected a credential-provider error, got {error:?}");
    };
    assert_eq!(*scheme, "bearerAuth");
    assert_eq!(source.to_string(), "identity provider unavailable");
    assert!(!error.is_transient());
    // The chain a generic error reporter walks: the request error, then the provider's own.
    let cause = std::error::Error::source(&error).expect("the request error");
    assert_eq!(
        cause.to_string(),
        "the token provider registered for security scheme `bearerAuth` failed"
    );
    let provider = std::error::Error::source(cause).expect("the provider's error");
    assert!(provider.downcast_ref::<AuthError>().is_some());
    println!("failed token provider surfaced as a typed error for `{scheme}`");
    assert_eq!(
        MOCK_REQUESTS.load(Ordering::SeqCst),
        requests_before,
        "a failed provider must fail before the request is sent"
    );

    // A wrong token draws the server's (undocumented) 401: preserved raw, and not retry-worthy.
    let wrong = Client::new(&base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from("nope")));
    match wrong.get_pet("1").await {
        Err(error @ Error::UnexpectedStatus { status, .. }) if status == 401 => {
            assert!(!error.is_transient());
            println!("undocumented 401 preserved for forensics");
        }
        other => panic!("expected an unexpected-status error, got {other:?}"),
    }

    // A refused connection is a transport failure, and retry-worthy — not a malformed request.
    // reqwest reports every failed send as a request-kind error, a refused connect included, so
    // this is the case a classifier keyed on `is_request()` alone gets wrong. The port is one the
    // OS just handed out and this process released, so nothing is listening on it.
    let closed = {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind a throwaway port");
        listener.local_addr().unwrap()
    };
    let unreachable = Client::new(&format!("http://{closed}"))
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));
    match unreachable.get_pet("1").await {
        Err(error @ Error::Transport(_)) => {
            assert!(error.is_transient());
            println!("refused connection classified as a transient transport failure");
        }
        other => panic!("expected a transport error for a refused connection, got {other:?}"),
    }

    // Bring-your-own-policy retry: wrap the default transport in a `RetryBackend` and install it via
    // `Client::with_backend`. The flaky route returns 503 once (a transient outcome) then 200; the
    // policy retries with a tokio-timed exponential backoff, so the call ultimately succeeds. The
    // client itself is unchanged — retry is a transport-seam wrapper, not a code path in `Client`.
    let retry_backend: Arc<dyn HttpBackend> = Arc::new(RetryBackend::new(
        Arc::new(ReqwestBackend::new(reqwest::Client::new())),
        Arc::new(ExponentialBackoff { max_retries: 5 }),
    ));
    let retrying = Client::with_backend(retry_backend, &base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));
    let recovered = retrying
        .get_pet("flaky")
        .await
        .expect("retry recovers from the transient 503");
    assert_eq!(recovered.status(), 200);
    assert_eq!(recovered.into_inner().name, "Comet");
    // The route was hit more than once, proving the retry actually replayed the request.
    assert!(FLAKY_HITS.load(Ordering::SeqCst) >= 2);
    println!(
        "retry recovered a flaky route after {} attempt(s)",
        FLAKY_HITS.load(Ordering::SeqCst)
    );

    println!("petstore example: all checks passed");
}

/// A deliberately tiny HTTP/1.1 mock on an ephemeral localhost port — no external service is
/// involved, so running this example repeatedly can't spam anyone.
fn spawn_mock_server() -> SocketAddr {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind mock server");
    let addr = listener.local_addr().unwrap();
    std::thread::spawn(move || {
        for stream in listener.incoming().flatten() {
            std::thread::spawn(move || handle(stream));
        }
    });
    addr
}

fn handle(mut stream: TcpStream) {
    let mut reader = BufReader::new(stream.try_clone().expect("clone stream"));
    let mut request_line = String::new();
    if reader.read_line(&mut request_line).is_err() {
        return;
    }
    MOCK_REQUESTS.fetch_add(1, Ordering::SeqCst);
    let mut parts = request_line.split_whitespace();
    let (Some(method), Some(target)) = (parts.next(), parts.next()) else {
        return;
    };
    let (path, query) = match target.split_once('?') {
        Some((path, query)) => (path, query),
        None => (target, ""),
    };

    let mut authorization = String::new();
    let mut content_type = String::new();
    let mut content_length = 0usize;
    loop {
        let mut line = String::new();
        if reader.read_line(&mut line).is_err() || line.trim().is_empty() {
            break;
        }
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        match name.to_ascii_lowercase().as_str() {
            "authorization" => authorization = value.trim().to_owned(),
            "content-type" => content_type = value.trim().to_owned(),
            "content-length" => content_length = value.trim().parse().unwrap_or(0),
            _ => {}
        }
    }
    let mut body = vec![0u8; content_length];
    if content_length > 0 && reader.read_exact(&mut body).is_err() {
        return;
    }

    // Extra response headers the route wants to add on top of the fixed ones.
    let mut extra_headers = String::new();

    let (status, response_body) = if authorization != format!("Bearer {TOKEN}") {
        (
            "401 Unauthorized",
            r#"{"message":"unauthorized"}"#.to_owned(),
        )
    } else {
        match (method, path) {
            ("GET", "/pets") => {
                // `deepObject` sends one bracketed pair per member, and an absent member sends
                // nothing at all — a JSON blob or a `filter=name,Rex` join would both be wrong.
                assert!(
                    query.contains("filter%5Bname%5D=Rex"),
                    "deepObject filter must travel as filter[name]=Rex: {query}"
                );
                assert!(
                    !query.contains("filter%5Btag%5D"),
                    "an absent deepObject member must not be sent: {query}"
                );
                extra_headers.push_str("X-Total-Count: 1\r\n");
                (
                    "200 OK",
                    r#"[{"id":"1","name":"Rex","status":"available"}]"#.to_owned(),
                )
            }
            ("POST", "/pets/1/photo") => {
                // Every part carries the Content-Type the Encoding Object declared for it.
                assert!(
                    content_type.starts_with("multipart/form-data; boundary="),
                    "photo upload must be multipart: {content_type}"
                );
                let text = String::from_utf8_lossy(&body);
                for (part, declared) in [("photo", "image/png"), ("meta", "application/json")] {
                    let at = text
                        .find(&format!("name=\"{part}\""))
                        .unwrap_or_else(|| panic!("part `{part}` missing: {text}"));
                    let header = text[at..].split("\r\n\r\n").next().unwrap_or("");
                    assert!(
                        header.contains(&format!("Content-Type: {declared}")),
                        "part `{part}` must declare {declared}: {header}"
                    );
                }
                ("204 No Content", String::new())
            }
            ("POST", "/pets") => {
                let new: serde_json::Value = serde_json::from_slice(&body).unwrap_or_default();
                let name = new["name"].as_str().unwrap_or("unnamed");
                if name == "Taken" {
                    // A problem type the description does not list.
                    (
                        "409 Conflict",
                        r#"{"type":"https://petstore.example/problems/name-reserved","title":"Name reserved","status":409,"detail":"`Taken` is held for a sold pet."}"#
                            .to_owned(),
                    )
                } else {
                    (
                        "201 Created",
                        format!(r#"{{"id":"2","name":"{name}","status":"available"}}"#),
                    )
                }
            }
            ("GET", "/pets/1") => (
                "200 OK",
                r#"{"id":"1","name":"Rex","status":"available"}"#.to_owned(),
            ),
            // A transiently-failing route: 503 on the first hit, 200 afterward. Exercises the
            // retry adapter — a plain client sees the 503, a retrying one recovers.
            ("GET", "/pets/flaky") => {
                if FLAKY_HITS.fetch_add(1, Ordering::SeqCst) == 0 {
                    (
                        "503 Service Unavailable",
                        r#"{"message":"try again"}"#.to_owned(),
                    )
                } else {
                    (
                        "200 OK",
                        r#"{"id":"flaky","name":"Comet","status":"available"}"#.to_owned(),
                    )
                }
            }
            ("GET", _) => ("404 Not Found", r#"{"message":"no such pet"}"#.to_owned()),
            ("DELETE", "/pets/1") => ("204 No Content", String::new()),
            ("DELETE", "/pets/3") => (
                "409 Conflict",
                r#"{"type":"https://petstore.example/problems/pet-has-orders","title":"Pet has orders","detail":"pet 3 has an open order."}"#
                    .to_owned(),
            ),
            // Pet 1 echoes the stored pet; pet 2 acknowledges with an empty 204.
            ("PUT", "/pets/1") => {
                let new: serde_json::Value = serde_json::from_slice(&body).unwrap_or_default();
                let name = new["name"].as_str().unwrap_or("unnamed");
                (
                    "200 OK",
                    format!(r#"{{"id":"1","name":"{name}","status":"available"}}"#),
                )
            }
            ("PUT", "/pets/2") => ("204 No Content", String::new()),
            _ => (
                "500 Internal Server Error",
                r#"{"message":"unhandled route"}"#.to_owned(),
            ),
        }
    };

    let _ = write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: application/json\r\n{extra_headers}Content-Length: {}\r\nConnection: close\r\n\r\n{response_body}",
        response_body.len(),
    );
}
