//! Drives the generated petstore client end to end against a local mock server: typed models,
//! query/header/path parameters, JSON bodies, bearer auth, typed API errors, undocumented-status
//! handling, the transient-failure classifier, and the bring-your-own-policy retry adapter.
//! Everything runs on 127.0.0.1 — no external API, no real credentials.

use std::future::Future;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::pin::Pin;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::Arc;
use std::time::Duration;

use secrecy::SecretString;

// The client generated by build.rs. Its file carries no inner attributes, so it can be included
// straight from OUT_DIR; `spargen generate --out src/petstore.rs` + `mod petstore;` works too.
mod petstore {
    include!(concat!(env!("OUT_DIR"), "/petstore.rs"));
}

use petstore::{
    exponential_backoff, types, Client, Credential, Error, HttpBackend, ReqwestBackend,
    RetryBackend, RetryOutcome, RetryPolicy,
};

const TOKEN: &str = "let-me-in";

/// How many times the flaky route has been hit; it fails transiently (503) on the first attempt,
/// then serves 200 — so a retrying client succeeds where a plain one would surface the 503.
static FLAKY_HITS: AtomicU32 = AtomicU32::new(0);

/// A bring-your-own retry policy: retry transient outcomes with exponential backoff, up to a cap.
/// The wait is built from the caller's own async timer (`tokio::time::sleep`) — the spargen runtime
/// ships no timer and never depends on tokio; timing is supplied here.
struct ExponentialBackoff {
    max_retries: u32,
}

impl RetryPolicy for ExponentialBackoff {
    fn retry<'a>(
        &'a self,
        attempt: u32,
        outcome: &RetryOutcome<'_>,
    ) -> Option<Pin<Box<dyn Future<Output = ()> + Send + 'a>>> {
        if attempt < self.max_retries && outcome.is_transient() {
            let wait =
                exponential_backoff(attempt, Duration::from_millis(10), Duration::from_millis(200));
            Some(Box::pin(tokio::time::sleep(wait)))
        } else {
            None
        }
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let addr = spawn_mock_server();
    let base_url = format!("http://{addr}");
    println!("mock petstore listening on {base_url}");

    let client = Client::new(&base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));

    // List with query + header parameters, built via the fluent optional-param setters.
    let pets = client
        .list_pets(Some(
            petstore::ListPetsParams::default()
                .limit(10)
                .status(types::Status::Available)
                .x_request_id("example-1".to_owned()),
        ))
        .await
        .expect("list_pets");
    assert_eq!(pets.status(), 200);
    let pets = pets.into_inner();
    assert_eq!(pets.len(), 1);
    println!("listed {} available pet(s): {}", pets.len(), pets[0].name);

    // Create with a typed JSON body.
    let created = client
        .create_pet(&types::NewPet {
            name: "Bella".to_owned(),
            tag: Some("dog".to_owned()),
        })
        .await
        .expect("create_pet");
    assert_eq!(created.status(), 201);
    let created = created.into_inner();
    println!("created pet #{} ({})", created.id, created.name);

    // Fetch by path parameter.
    let pet = client.get_pet("1".to_owned()).await.expect("get_pet");
    assert_eq!(pet.into_inner().status, types::Status::Available);
    println!("fetched pet #1");

    // A documented 404 arrives as the operation's typed error body.
    match client.get_pet("999".to_owned()).await {
        Err(Error::Api(response)) => {
            assert_eq!(response.status(), 404);
            println!("typed 404: {}", response.into_inner().message);
        }
        other => panic!("expected a typed 404, got {other:?}"),
    }

    // 204 maps to a unit body.
    let deleted = client.delete_pet("1".to_owned()).await.expect("delete_pet");
    assert_eq!(deleted.status(), 204);
    println!("deleted pet #1");

    // A missing credential fails before anything is sent — never a silent 401.
    let unauthenticated = Client::new(&base_url).unwrap();
    match unauthenticated.get_pet("1".to_owned()).await {
        Err(Error::RequestConstruction(error)) => {
            println!("missing credential rejected up front: {error}");
        }
        other => panic!("expected a request-construction error, got {other:?}"),
    }

    // A wrong token draws the server's (undocumented) 401: preserved raw, and not retry-worthy.
    let wrong = Client::new(&base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from("nope")));
    match wrong.get_pet("1".to_owned()).await {
        Err(error @ Error::UnexpectedStatus { status, .. }) if status == 401 => {
            assert!(!error.is_transient());
            println!("undocumented 401 preserved for forensics");
        }
        other => panic!("expected an unexpected-status error, got {other:?}"),
    }

    // Bring-your-own-policy retry: wrap the default transport in a `RetryBackend` and install it via
    // `Client::with_backend`. The flaky route returns 503 once (a transient outcome) then 200; the
    // policy retries with a tokio-timed exponential backoff, so the call ultimately succeeds. The
    // client itself is unchanged — retry is a transport-seam wrapper, not a code path in `Client`.
    let retry_backend: Arc<dyn HttpBackend> = Arc::new(RetryBackend::new(
        Arc::new(ReqwestBackend::new(reqwest::Client::new())),
        Arc::new(ExponentialBackoff { max_retries: 5 }),
    ));
    let retrying = Client::with_backend(retry_backend, &base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));
    let recovered = retrying
        .get_pet("flaky".to_owned())
        .await
        .expect("retry recovers from the transient 503");
    assert_eq!(recovered.status(), 200);
    assert_eq!(recovered.into_inner().name, "Comet");
    // The route was hit more than once, proving the retry actually replayed the request.
    assert!(FLAKY_HITS.load(Ordering::SeqCst) >= 2);
    println!(
        "retry recovered a flaky route after {} attempt(s)",
        FLAKY_HITS.load(Ordering::SeqCst)
    );

    println!("petstore example: all checks passed");
}

/// A deliberately tiny HTTP/1.1 mock on an ephemeral localhost port — no external service is
/// involved, so running this example repeatedly can't spam anyone.
fn spawn_mock_server() -> SocketAddr {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind mock server");
    let addr = listener.local_addr().unwrap();
    std::thread::spawn(move || {
        for stream in listener.incoming().flatten() {
            std::thread::spawn(move || handle(stream));
        }
    });
    addr
}

fn handle(mut stream: TcpStream) {
    let mut reader = BufReader::new(stream.try_clone().expect("clone stream"));
    let mut request_line = String::new();
    if reader.read_line(&mut request_line).is_err() {
        return;
    }
    let mut parts = request_line.split_whitespace();
    let (Some(method), Some(target)) = (parts.next(), parts.next()) else {
        return;
    };
    let path = target.split('?').next().unwrap_or(target);

    let mut authorization = String::new();
    let mut content_length = 0usize;
    loop {
        let mut line = String::new();
        if reader.read_line(&mut line).is_err() || line.trim().is_empty() {
            break;
        }
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        match name.to_ascii_lowercase().as_str() {
            "authorization" => authorization = value.trim().to_owned(),
            "content-length" => content_length = value.trim().parse().unwrap_or(0),
            _ => {}
        }
    }
    let mut body = vec![0u8; content_length];
    if content_length > 0 && reader.read_exact(&mut body).is_err() {
        return;
    }

    let (status, response_body) = if authorization != format!("Bearer {TOKEN}") {
        ("401 Unauthorized", r#"{"message":"unauthorized"}"#.to_owned())
    } else {
        match (method, path) {
            ("GET", "/pets") => (
                "200 OK",
                r#"[{"id":"1","name":"Rex","status":"available"}]"#.to_owned(),
            ),
            ("POST", "/pets") => {
                let new: serde_json::Value = serde_json::from_slice(&body).unwrap_or_default();
                let name = new["name"].as_str().unwrap_or("unnamed");
                (
                    "201 Created",
                    format!(r#"{{"id":"2","name":"{name}","status":"available"}}"#),
                )
            }
            ("GET", "/pets/1") => (
                "200 OK",
                r#"{"id":"1","name":"Rex","status":"available"}"#.to_owned(),
            ),
            // A transiently-failing route: 503 on the first hit, 200 afterward. Exercises the
            // retry adapter — a plain client sees the 503, a retrying one recovers.
            ("GET", "/pets/flaky") => {
                if FLAKY_HITS.fetch_add(1, Ordering::SeqCst) == 0 {
                    (
                        "503 Service Unavailable",
                        r#"{"message":"try again"}"#.to_owned(),
                    )
                } else {
                    (
                        "200 OK",
                        r#"{"id":"flaky","name":"Comet","status":"available"}"#.to_owned(),
                    )
                }
            }
            ("GET", _) => ("404 Not Found", r#"{"message":"no such pet"}"#.to_owned()),
            ("DELETE", "/pets/1") => ("204 No Content", String::new()),
            _ => (
                "500 Internal Server Error",
                r#"{"message":"unhandled route"}"#.to_owned(),
            ),
        }
    };

    let _ = write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{response_body}",
        response_body.len(),
    );
}
